#+TITLE: Updated Dactyl Build Guide

** Parts List

Things you'll need.



| Parts:                            | Cost in USD: |
|-----------------------------------+--------------|
| 3D Printed Shells                 |       100.00 |
|-----------------------------------+--------------|
| 70ct Key Switches                 |        50.00 |
|-----------------------------------+--------------|
| Rubber O-Rings for Switches       |         2.00 |
|-----------------------------------+--------------|
| Key Caps                          |        50.00 |
|-----------------------------------+--------------|
| Pyralux (Flexible copper for PCB) |        30.00 |
|-----------------------------------+--------------|
| Total:                            |    total([]) |
|                                   |              |
#+TBLFM: $2=total($1..$5)

- Price considerations
  This table represents what I purchased my hartware for. YMMV.
- You can get switch-dampening o-rings for as little as $2.00 if you're willing
  to wait for them to ship from China.
- I splurged on my keycaps. Generally you're going to see them on Ali Express at
  around the $50-$60 price point.

*** Retailers
- [[https://www.aliexpress.com]]
- [[https://www.digikey.com]]
[[- https://www.kbdfans.com]]

** Part Dimensions & Other Considerations

| Part:                     | Dimension or special consideration: |
|---------------------------+-------------------------------------|
| Screws                    |                                     |
|---------------------------+-------------------------------------|
| Standoffs                 |                                     |
|---------------------------+-------------------------------------|
| Rubber feet               |                                     |
|---------------------------+-------------------------------------|

*** Key Switches
- Switch Type: It's best to use SMD (Surface Mount Device) switches. I purchased regular ones
  and ended up clipping all of the little plastic orientation pins off. Not a
  huge deal, but SMD switches are what you want
- Cherry MX: is the premium key switch brand on the market. I highly recommend
  one of the 9 switch testers you can pick up for about $13.00. Tere are about
  3 steps in variation between no clicks to loud clicks & linear feel to tactile feel.
- Knockoffs: I've only had experience with Gaterons. They are very much like
  Cherry MXs but have much less of a tactile feel. A good rule of thumb is to get
  the next most tactile model above whatever Cherry MX switch you prefer.

*** Key Caps
**** Profile:
If you look at a mechanical keyboard from the side, you'll notice that the tops
of the keys form a curve to allow for better comfort while typing. There are
different styles available out there for this. For the Dactyl, the SA profile
will be the best.
- OEM:
- SA:

**** Material:
You'll see two main types of material more than any others: ABS & PBT.
- ABS: The advantege of ABS is that it's more cost-effective (cheaper).
  The disadvantage is that it fades over time. If you're spending a lot on your
  keycaps and want them to last you should consider this.
- PBT:

** Step-by-step instructions
*** Preparation
Use soldering iron to push countersunk screws into plastic shell.
Before wiring, be sure to heatshrink the standoffs to prevent shorts. I found 1/8"
heatshrink tubing works best.

*** Circuit design
*** Notes on Xerox direct-print to Pyralux

*** Etching

*** Wiring
**** TODO Prerequisites
- How does this work?
- Key matrix explanation
**** Diode position (Row-driven vs. Column-driven )
You will need to consider the position of the diodes depending upon how you want
the current from your microcontroller to flow.
For a row-driven keyboard, the cathode ends of the diodes should face away from the switch pin. This
allows the current to flow from the row, through the switch and out through the column.

*** PCB Layering instructions

*** Firmware guide
**** config.qmk.fm
- Under board, choose 'handwired/dactyl'.
- Change defaults as necessary.
- Click on 'COMPILE'.
- Once finished, download the .hex file by clicking 'FIRMWARE'. (Consider saving the keymap.json file for future reference.)
- For MacOS & Windows, use the qmk-toolbox application to flash the Teensy 2.0. Follow gui instructions.
- For GNU+Linux, use your package manager to search for the teensy-loader-cli
  (or some variation therof) command-line tool. Use the following syntax to
  flash your chosen hex file: =$ teensy-loader-cli -mmcu=atmega32u4 -wv path/to/file.hex=
