#+TITLE: Dactyl-ToDo

* Updated Dactyl Build Guide
** Parts List (This is what I spent on parts)

| Parts:                            | Cost in USD: |
|-----------------------------------+--------------|
| 3D Printed Shells                 |       400000 |
|-----------------------------------+--------------|
| Key Switches                      |       500000 |
|-----------------------------------+--------------|
| Key Caps                          |       500000 |
|-----------------------------------+--------------|
| Pyralux (Flexible copper for PCB) |       600000 |
|-----------------------------------+--------------|
| Total:                            |    total([]) |
#+TBLFM: $2=total($0..$4)

*** Retailers


** Dimensions
- Screws
- Standoffs
- Rubber feet

** Step-by-step instructions
*** Preparation
Use soldering iron to push countersunk screws into plastic shell.
Before wiring, be sure to heatshrink the standoffs to prevent shorts. I found 1/8"
heatshrink tubing works best.

*** Circuit design

*** Etching

*** Wiring
**** TODO Prerequisites
- How does this work?
Key matrix explanation
**** Diode position (Row-driven vs. Column-driven )
You will need to consider the position of the diodes depending upon how you want
the current from your microcontroller to flow.
For a row-driven keyboard, the cathode ends of the diodes should face away from the switch pin. This
allows the current to flow from the row, through the switch and out through the column.

*** PCB Layering instructions

*** Firmware guide
**** config.qmk.fm
- Under board, choose 'handwired/dactyl'.
- Change defaults as necessary.
- Click on 'COMPILE'.
- Once finished, download the .hex file by clicking 'FIRMWARE'. (Consider saving the keymap.json file for future reference.)
- For MacOS & Windows, use the qmk-toolbox application to flash the Teensy 2.0. Follow gui instructions.
- For GNU+Linux, use your package manager to search for the teensy-loader-cli
  (or some variation therof) command-line tool. Use the following syntax to
  flash your chosen hex file: `$ teensy-loader-cli -mmcu=atmega32u4 -wv path/to/file.hex`
