#+TITLE: Dactyl-ToDo

* Organize & Commit Personal Work to Github
** PCB Design
** Take Dimensions for standoffs, screws & rubber feet
** Step-by-step instructions
*** Updated parts list
*** Heatshrink standoffs
*** PCB Layering instructions
*** Diode position
For a row-driven keyboard, the cathode ends of the diodes should face away from the switch pin. This
allows the current to flow from the row, through the switch and out through the column.
*** Firmware guide
**** config.qmk.fm
Under board, choose 'handwired/dactyl'.
Change defaults as necessary.
Click on 'COMPILE'.
Once finised, download the .hex file by clicking 'FIRMWARE'.
- Consider saving the keymap.json file for future reference.
For MacOS & Windows, use the qmk-toolbox application to flash the Teensy 2.0.
Follow gui instructions.
For GNU+Linux, use your package manager to search for the teensy-loader-cli (or
some variation therof) command-line tool. Use the following syntax to flash your
chosen hex file:
- $ teensy-loader-cli -mmcu=atmega32u4 -wv path/to/file.hex
